// Temporary debug screen copy; removed with the screen when the Test UI lands.
export const debugContent = {
  title: 'Speed test (debug)',
  start: 'Start',
  stop: 'Stop',
  present: 'present',
  missing: 'missing',
  empty: '—',
  rows: {
    status: 'Status',
    phase: 'Phase',
    server: 'Server',
    download: 'Download',
    upload: 'Upload',
    idle: 'Idle ping',
    loaded: 'Loaded ping',
    elapsed: 'Elapsed',
    nativeModule: 'Native module',
    stallIdle: 'JS stall (idle)',
    stallDownload: 'JS stall (download)',
    stallUpload: 'JS stall (upload)',
    error: 'Error',
  },
  mbps: (value: string) => `${value} Mbps`,
  ms: (value: string) => `${value} ms`,
  seconds: (value: string) => `${value} s`,
  stall: (maxMs: number, avgMs: number) => `max ${maxMs} ms · avg ${avgMs} ms`,
} as const;
